sudo: required

services:
- docker

language: bash

install:
- sudo apt update
- sudo apt install -y qemu qemu-user-static qemu-user binfmt-support

script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t gmaslowski/rpi-cron-speedtest:latest-arm .
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker push gmaslowski/rpi-cron-speedtest:latest-arm
    docker run --rm -ti weshigbee/manifest-tool --username $DOCKER_USER --password $DOCKER_PASS push from-args --platforms linux/arm --target gmaslowski/rpi-cron-speedtest:latest --template gmaslowski/rpi-cron-speedtest:latest-ARCH
  fi
